functional:
 - Регистрация пользователей
 - Аутентификация пользователей
 - Восстановление забытых паролей
 - Поиск пользователей по ключевым словам
 - Рейтинг игроков
 - Поддержка популярных языков программирования для проведения CODE BATTLE
 - Возможность провести CODE BATTLE с ботом без регистрации
 - Возможность зарегистрированному пользователю проводить CODE BATTLE с любым пользователем сайта, ботом или пригласить друга
 - Возможность игры по времени, при определенных обстоятельствах сдаться 
 - Возможность во время игры выполнить разрешенные настройки, проверить код, общаться по чату
 - По окончании игры получить сообщение о победе, проигрыше
non-functional:
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен быть удобным при использовании на мобильном устройстве
 - Сайт должен быть способен обрабатывать большое количество трафика
 - Сайт должен быть удобным в использования, интуитивно понятное меню
 - Сайт должен быть оптимизирован для скорости работы
 - Сайт должен быть совместим с последними версиями браузеров
 - Сайт должен работать по протоколу https
implicit:
 - Общедоступность
 - Сайт должен поддерживать русский и английский язык
