functional:
 - Регистрация пользователей
 - Аутентификация пользователей
 - Создание профилей пользователей
 - Восстановление забытых паролей
 - Поиск по сайту по ключевым словам
 - Возможность оставлять комментарии, отзывы, обратную связь
 - Возможность прикрепления файлов к комментариям
 - Оптимизация для поисковых систем (SEO)
 - Настройка мета-тегов для улучшения индексации
 - Мониторинг активности пользователей, рейтинги игроков
 - Поддержка популярных языков программирования для проведения CODE BATTLE
 - Возможность провести CODE BATTLE без регистрации
 - Возможность зарегистрированному пользователю проводить CODE BATTLE с любым пользователем сайта или ботом
non-functional:
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен быть удобным на мобильном устройстве
 - Сайт должен быть способен обрабатывать большое количество трафика
 - Сайт должен быть удобным в использования, интуитивно понятное меню
 - Сайт должен быть оптимизирован для скорости работы
 - Сайт должен быть совместим с последними версиями браузеров
 - Сайт должен работать по протоколу https
implicit:
 - Общедоступность
